---
- hosts: localhost
  become: yes
  tasks :
    - name: Echoing Hello
      shell: Echo "Hello"
    
    - name: Install httpd
      yum:
        name: httpd
        state: latest 

    - name: Ensure HTTPD is started
      service: 
        name: sshd
        state: started